-- Jalankan file ini di Supabase SQL Editor (sekali saja).
-- Tujuan:
-- 1) Buat tabel alat_kalibrasi untuk data permanen
-- 2) Buat tabel jadwal_onsite untuk dashboard
-- 3) Aktifkan RLS sesuai role admin/teknisi/direktur/manager
-- 4) Siapkan trigger updated_at

create table if not exists public.alat_kalibrasi (
  id bigint generated by default as identity primary key,
  kode_alat text not null,
  nama_alat text not null,
  jenis_layanan text not null,
  tanggal_masuk date not null default current_date,
  status_kalibrasi text not null default 'MENUNGGU'
    check (status_kalibrasi in ('MENUNGGU', 'PENDING_CUSTOMER', 'PROSES', 'SELESAI', 'DIAMBIL', 'DIBATALKAN')),
  tanggal_diambil date null,
  dokumen_nama text null,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.alat_kalibrasi
  drop constraint if exists alat_kalibrasi_status_kalibrasi_check;

alter table public.alat_kalibrasi
  add constraint alat_kalibrasi_status_kalibrasi_check
  check (status_kalibrasi in ('MENUNGGU', 'PENDING_CUSTOMER', 'PROSES', 'SELESAI', 'DIAMBIL', 'DIBATALKAN'));

alter table public.alat_kalibrasi
  add column if not exists no_order text,
  add column if not exists no_sertifikat text,
  add column if not exists spesifikasi text,
  add column if not exists jumlah integer,
  add column if not exists onsite_inlab text,
  add column if not exists lab text,
  add column if not exists pesanan_khusus text,
  add column if not exists remarks text,
  add column if not exists dokumen_nama text,
  add column if not exists dokumen text;

alter table if exists public.alat_masuk
  add column if not exists created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  add column if not exists onsite_inlab text,
  add column if not exists remarks text,
  add column if not exists status_layanan text not null default 'MENUNGGU',
  add column if not exists dokumen text,
  add column if not exists dokumen_nama text;

update public.alat_kalibrasi
set status_kalibrasi = case
  when upper(trim(status_kalibrasi)) in ('PROSES KALIBRASI', 'PROSES') then 'PROSES'
  when upper(trim(status_kalibrasi)) in ('SELESAI KALIBRASI', 'SELESAI') then 'SELESAI'
  when upper(trim(status_kalibrasi)) in ('PENDING CUSTOMER', 'PENDING_CUSTOMER') then 'PENDING_CUSTOMER'
  when upper(trim(status_kalibrasi)) = 'DIAMBIL' then 'DIAMBIL'
  when upper(trim(status_kalibrasi)) = 'DIBATALKAN' then 'DIBATALKAN'
  else 'MENUNGGU'
end
where status_kalibrasi is not null;

update public.alat_masuk
set status_layanan = case
  when upper(trim(status_layanan)) in ('PROSES KALIBRASI', 'PROSES') then 'PROSES'
  when upper(trim(status_layanan)) in ('SELESAI KALIBRASI', 'SELESAI') then 'SELESAI'
  when upper(trim(status_layanan)) in ('PENDING CUSTOMER', 'PENDING_CUSTOMER') then 'PENDING_CUSTOMER'
  when upper(trim(status_layanan)) = 'DIAMBIL' then 'DIAMBIL'
  when upper(trim(status_layanan)) = 'DIBATALKAN' then 'DIBATALKAN'
  else 'MENUNGGU'
end
where status_layanan is not null;

alter table if exists public.alat_masuk
  drop constraint if exists alat_masuk_status_layanan_check;

alter table if exists public.alat_masuk
  add constraint alat_masuk_status_layanan_check
  check (status_layanan in ('MENUNGGU', 'PENDING_CUSTOMER', 'PROSES', 'SELESAI', 'DIAMBIL', 'DIBATALKAN'));

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'alat_masuk'
      and column_name = 'created_by'
      and data_type <> 'uuid'
  ) then
    alter table public.alat_masuk
      alter column created_by drop default,
      alter column created_by type uuid using (
        case
          when created_by is null then null
          when trim(created_by::text) ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$'
            then trim(created_by::text)::uuid
          else null
        end
      );
  end if;
end $$;

alter table if exists public.alat_masuk
  alter column created_by set default auth.uid();

alter table if exists public.alat_masuk
  drop constraint if exists alat_masuk_created_by_fkey;

alter table if exists public.alat_masuk
  add constraint alat_masuk_created_by_fkey
  foreign key (created_by) references auth.users(id) on delete set null;

grant usage on schema public to authenticated;
grant select, insert, update, delete on table public.alat_masuk to authenticated;

alter table if exists public.alat_masuk enable row level security;

do $$
declare
  policy_name text;
begin
  for policy_name in
    select pol.polname
    from pg_policy pol
    join pg_class cls on cls.oid = pol.polrelid
    join pg_namespace nsp on nsp.oid = cls.relnamespace
    where nsp.nspname = 'public'
      and cls.relname = 'alat_masuk'
  loop
    execute format('drop policy if exists %I on public.alat_masuk;', policy_name);
  end loop;
end $$;

drop policy if exists "alat_masuk_select_own" on public.alat_masuk;
drop policy if exists "alat_masuk_insert_own" on public.alat_masuk;
drop policy if exists "alat_masuk_update_own" on public.alat_masuk;
drop policy if exists "alat_masuk_delete_own" on public.alat_masuk;
drop policy if exists "temporary_full_access" on public.alat_masuk;
drop policy if exists "dev_full_access_alat_masuk" on public.alat_masuk;

drop policy if exists "authenticated_insert_alat_masuk" on public.alat_masuk;
drop policy if exists "authenticated_select_alat_masuk" on public.alat_masuk;
drop policy if exists "authenticated_update_alat_masuk" on public.alat_masuk;
drop policy if exists "authenticated_delete_alat_masuk" on public.alat_masuk;

create policy "authenticated_insert_alat_masuk"
on public.alat_masuk
for insert
to authenticated
with check (auth.uid() = created_by);

create policy "authenticated_select_alat_masuk"
on public.alat_masuk
for select
to authenticated
using (auth.uid() = created_by or created_by is null);

create policy "authenticated_update_alat_masuk"
on public.alat_masuk
for update
to authenticated
using (auth.uid() = created_by or created_by is null)
with check (auth.uid() = created_by);

create policy "authenticated_delete_alat_masuk"
on public.alat_masuk
for delete
to authenticated
using (auth.uid() = created_by);

-- ONLY FOR DEVELOPMENT (sementara)
-- create policy "dev_full_access_alat_masuk"
-- on public.alat_masuk
-- for all
-- to authenticated
-- using (true)
-- with check (true);

update public.alat_kalibrasi
set no_order = kode_alat
where no_order is null;

create index if not exists idx_alat_kalibrasi_tanggal_masuk
  on public.alat_kalibrasi (tanggal_masuk desc);

create index if not exists idx_alat_kalibrasi_status
  on public.alat_kalibrasi (status_kalibrasi);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.current_profile_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select lower(trim(p.role))
  from public."Profile" p
  where p.id = auth.uid()
  limit 1
$$;

grant execute on function public.current_profile_role() to authenticated;

alter table public."Profile"
  add column if not exists username text;

create unique index if not exists idx_profile_username_unique
  on public."Profile" (lower(trim(username)))
  where username is not null and trim(username) <> '';

drop trigger if exists trg_alat_kalibrasi_updated_at on public.alat_kalibrasi;
create trigger trg_alat_kalibrasi_updated_at
before update on public.alat_kalibrasi
for each row
execute function public.set_updated_at();

alter table public.alat_kalibrasi enable row level security;

drop policy if exists "alat_select_authenticated" on public.alat_kalibrasi;
create policy "alat_select_authenticated"
on public.alat_kalibrasi
for select
to authenticated
using (true);

drop policy if exists "alat_insert_admin" on public.alat_kalibrasi;
create policy "alat_insert_admin"
on public.alat_kalibrasi
for insert
to authenticated
with check (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) = 'admin'
  )
);

drop policy if exists "alat_update_admin_teknisi" on public.alat_kalibrasi;
create policy "alat_update_admin_teknisi"
on public.alat_kalibrasi
for update
to authenticated
using (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) in ('adminutama', 'admin', 'teknisi', 'supervisor', 'direktur')
  )
)
with check (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) in ('adminutama', 'admin', 'teknisi', 'supervisor', 'direktur')
  )
);

drop policy if exists "alat_delete_admin" on public.alat_kalibrasi;
create policy "alat_delete_admin"
on public.alat_kalibrasi
for delete
to authenticated
using (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) = 'admin'
  )
);

create table if not exists public.jadwal_onsite (
  id bigint generated by default as identity primary key,
  tanggal_onsite date not null,
  pelanggan text not null,
  lokasi text not null,
  teknisi text null,
  jenis_layanan text null,
  status text not null default 'TERJADWAL'
    check (status in ('TERJADWAL', 'PROSES', 'SELESAI', 'BATAL')),
  catatan text null,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.jadwal_onsite
  add column if not exists no_order text,
  add column if not exists durasi_onsite text,
  add column if not exists remarks text;

create index if not exists idx_jadwal_onsite_tanggal
  on public.jadwal_onsite (tanggal_onsite asc);

create index if not exists idx_jadwal_onsite_status
  on public.jadwal_onsite (status);

drop trigger if exists trg_jadwal_onsite_updated_at on public.jadwal_onsite;
create trigger trg_jadwal_onsite_updated_at
before update on public.jadwal_onsite
for each row
execute function public.set_updated_at();

alter table public.jadwal_onsite enable row level security;

drop policy if exists "jadwal_onsite_select_authenticated" on public.jadwal_onsite;
create policy "jadwal_onsite_select_authenticated"
on public.jadwal_onsite
for select
to authenticated
using (true);

drop policy if exists "jadwal_onsite_insert_admin_manager_direktur" on public.jadwal_onsite;
drop policy if exists "jadwal_onsite_insert_direktur_manager" on public.jadwal_onsite;
create policy "jadwal_onsite_insert_direktur_manager"
on public.jadwal_onsite
for insert
to authenticated
with check (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and (
        lower(trim(p.role)) = 'direktur'
        or lower(trim(p.role)) like 'manager%'
      )
  )
);

drop policy if exists "jadwal_onsite_update_admin_manager_direktur" on public.jadwal_onsite;
drop policy if exists "jadwal_onsite_update_direktur_manager" on public.jadwal_onsite;
create policy "jadwal_onsite_update_direktur_manager"
on public.jadwal_onsite
for update
to authenticated
using (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and (
        lower(trim(p.role)) = 'direktur'
        or lower(trim(p.role)) like 'manager%'
      )
  )
)
with check (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and (
        lower(trim(p.role)) = 'direktur'
        or lower(trim(p.role)) like 'manager%'
      )
  )
);

drop policy if exists "jadwal_onsite_delete_admin_direktur" on public.jadwal_onsite;
drop policy if exists "jadwal_onsite_delete_direktur_manager" on public.jadwal_onsite;
create policy "jadwal_onsite_delete_direktur_manager"
on public.jadwal_onsite
for delete
to authenticated
using (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and (
        lower(trim(p.role)) = 'direktur'
        or lower(trim(p.role)) like 'manager%'
      )
  )
);

alter table public."Profile" enable row level security;

drop policy if exists "profile_select_authenticated" on public."Profile";
create policy "profile_select_authenticated"
on public."Profile"
for select
to authenticated
using (true);

drop policy if exists "profile_insert_pengaturan" on public."Profile";
create policy "profile_insert_pengaturan"
on public."Profile"
for insert
to authenticated
with check (
  public.current_profile_role() in ('direktur', 'managerkeuangan', 'managerpemasaran')
);

drop policy if exists "profile_update_pengaturan" on public."Profile";
create policy "profile_update_pengaturan"
on public."Profile"
for update
to authenticated
using (
  public.current_profile_role() in ('direktur', 'managerkeuangan', 'managerpemasaran')
)
with check (
  public.current_profile_role() in ('direktur', 'managerkeuangan', 'managerpemasaran')
);
