-- Jalankan file ini di Supabase SQL Editor (sekali saja).
-- Tujuan:
-- 1) Buat tabel alat_kalibrasi untuk data permanen
-- 2) Buat tabel jadwal_onsite untuk dashboard
-- 3) Aktifkan RLS sesuai role admin/teknisi/direktur/manager
-- 4) Siapkan trigger updated_at

create table if not exists public.alat_kalibrasi (
  id bigint generated by default as identity primary key,
  kode_alat text not null,
  nama_alat text not null,
  jenis_layanan text not null,
  tanggal_masuk date not null default current_date,
  status_kalibrasi text not null default 'MENUNGGU'
    check (status_kalibrasi in ('MENUNGGU', 'PROSES', 'SELESAI', 'DIAMBIL')),
  tanggal_diambil date null,
  dokumen_nama text null,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_alat_kalibrasi_tanggal_masuk
  on public.alat_kalibrasi (tanggal_masuk desc);

create index if not exists idx_alat_kalibrasi_status
  on public.alat_kalibrasi (status_kalibrasi);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_alat_kalibrasi_updated_at on public.alat_kalibrasi;
create trigger trg_alat_kalibrasi_updated_at
before update on public.alat_kalibrasi
for each row
execute function public.set_updated_at();

alter table public.alat_kalibrasi enable row level security;

drop policy if exists "alat_select_authenticated" on public.alat_kalibrasi;
create policy "alat_select_authenticated"
on public.alat_kalibrasi
for select
to authenticated
using (true);

drop policy if exists "alat_insert_admin" on public.alat_kalibrasi;
create policy "alat_insert_admin"
on public.alat_kalibrasi
for insert
to authenticated
with check (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) = 'admin'
  )
);

drop policy if exists "alat_update_admin_teknisi" on public.alat_kalibrasi;
create policy "alat_update_admin_teknisi"
on public.alat_kalibrasi
for update
to authenticated
using (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) in ('admin', 'teknisi')
  )
)
with check (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) in ('admin', 'teknisi')
  )
);

drop policy if exists "alat_delete_admin" on public.alat_kalibrasi;
create policy "alat_delete_admin"
on public.alat_kalibrasi
for delete
to authenticated
using (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) = 'admin'
  )
);

create table if not exists public.jadwal_onsite (
  id bigint generated by default as identity primary key,
  tanggal_onsite date not null,
  pelanggan text not null,
  lokasi text not null,
  teknisi text null,
  jenis_layanan text null,
  status text not null default 'TERJADWAL'
    check (status in ('TERJADWAL', 'PROSES', 'SELESAI', 'BATAL')),
  catatan text null,
  created_by uuid null default auth.uid() references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_jadwal_onsite_tanggal
  on public.jadwal_onsite (tanggal_onsite asc);

create index if not exists idx_jadwal_onsite_status
  on public.jadwal_onsite (status);

drop trigger if exists trg_jadwal_onsite_updated_at on public.jadwal_onsite;
create trigger trg_jadwal_onsite_updated_at
before update on public.jadwal_onsite
for each row
execute function public.set_updated_at();

alter table public.jadwal_onsite enable row level security;

drop policy if exists "jadwal_onsite_select_authenticated" on public.jadwal_onsite;
create policy "jadwal_onsite_select_authenticated"
on public.jadwal_onsite
for select
to authenticated
using (true);

drop policy if exists "jadwal_onsite_insert_admin_manager_direktur" on public.jadwal_onsite;
create policy "jadwal_onsite_insert_admin_manager_direktur"
on public.jadwal_onsite
for insert
to authenticated
with check (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) in ('admin', 'manager', 'direktur')
  )
);

drop policy if exists "jadwal_onsite_update_admin_manager_direktur" on public.jadwal_onsite;
create policy "jadwal_onsite_update_admin_manager_direktur"
on public.jadwal_onsite
for update
to authenticated
using (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) in ('admin', 'manager', 'direktur')
  )
)
with check (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) in ('admin', 'manager', 'direktur')
  )
);

drop policy if exists "jadwal_onsite_delete_admin_direktur" on public.jadwal_onsite;
create policy "jadwal_onsite_delete_admin_direktur"
on public.jadwal_onsite
for delete
to authenticated
using (
  exists (
    select 1
    from public."Profile" p
    where p.id = auth.uid()
      and lower(trim(p.role)) in ('admin', 'direktur')
  )
);
